### ISSUE TITLE
unicode normalization

### ISSUE THREAD

**Issue by rurban** [nalgeon/sqlean#10]
Unaccent is a nice feature, but fails with denormalized ordered sequences, and on all non-mark sequences, such as all non-european languages. There really should be normalization step added, like NFD, and maybe even add a field to cache this NFD string and a flag if already done (and equal as in 95% of all cases).

**Comment by nalgeon** [comment]
Yeah, probably. Unfortunately, I'm not nearly as good with Unicode (or C programming) as necessary to even try adding that.
