### ISSUE TITLE
How to do case insensitive REGEXP matching?

### ISSUE THREAD

**Issue by titanism** [nalgeon/sqlean#100]
We didn't see a way at least in the docs to pass a flag, e.g. `i` for case insensitivity.  Curious how this can be accomplished?

**Comment by nalgeon** [comment]
Yep, `(?i)` is the way to go. I've updated the [docs](https://github.com/nalgeon/sqlean/commit/7631ba21ead4f6671fa2cfb08155e022e14b3a4d). No plans for a separate flag at this time.
