### ISSUE TITLE
sqlite version compatibility

### ISSUE THREAD

**Issue by axxName** [nalgeon/sqlean#106]
According to src/sqlite3.h modules compiled for version:
#define SQLITE_VERSION        "3.44.2"

for older versions of SQLITE (in older linuxes) there is 'segmentation fault' when loading this modules
Example:Oracle Linux Server 7.7
sqlite3 --version3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
sqlite> .load ./statssqlite> select percentile(num,25) from test;
Segmentation fault (core dumped)

Need annotation about version applicability in README

**Comment by axxName** [comment]
And about glibc version compatibility too

ldd sqlean.so
./sqlean.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./sqlean.so)

**Comment by justinclift** [comment]
If you're ok to compile the `sqlean` source code on your system, rather than use the precompiled version, that should fix your immediate problem and get things working. :smile:

**Comment by nalgeon** [comment]
Sorry, I do not have the capacity to investigate the specific version compatibility. Building from source is always an option as Justin said.
