### ISSUE TITLE
incorrect results in percentile functions

### ISSUE THREAD

**Issue by axxName** [nalgeon/sqlean#107]
CREATE TABLE test (num INT);

insert into test values(1);
insert into test values(2);
insert into test values(3);
insert into test values(4);
insert into test values(9);

select percentile_75(num) from test;
sqlite> select percentile_75(num) from test;
4.0

But values in table are INTegers, not float!

**Comment by nalgeon** [comment]
The return type of the precentile function is real, regardless of its argument type.
