### ISSUE TITLE
`Runtime error: out of memory (7)` for any selection using vsv

### ISSUE THREAD

**Issue by astral-l** [nalgeon/sqlean#108]
When using the vsv extension, creating a table from a csv file and attempting to select any data from it fails immediately in an out-of-memory error, regardless of the size of the query.

SQLite version: 3.45.0

To reproduce:
- in example.csv:
```
id,data
1,foo
2,bar
3,baz
```

- on sqlite command line:
```
> SELECT load_extension('/path/to/vsv');

> CREATE VIRTUAL TABLE example USING vsv(
    filename=example.csv,
    schema="CREATE TABLE example(id INTEGER, data TEXT)"
);

> SELECT * FROM example;
```

**Comment by nalgeon** [comment]
Thanks for providing all the details! The `columns` parameter is required:

```
create virtual table example using vsv(
    filename=example.csv,
    schema="create table example(id integer, data text)",
    columns=2,
);
```

I'll fix the doc.
