### ISSUE TITLE
Missing pre-compiled binaries for linux-arm64

### ISSUE THREAD

**Issue by flaviomartins** [nalgeon/sqlean#112]
Hi,

I am trying to install sqlean inside a docker container running linux.

```
> installing nalgeon/sqlean...
! unsupported platform: linux-arm64
```

Can you add linux-arm64? I see it already has macos-arm64 pre-compiled binaries.

**Comment by nalgeon** [comment]
Sorry, no current plans for linux/arm64. Feel free to send a PR though.

**Comment by nalgeon** [comment]
Linux ARM supported as of [0.22.0](https://github.com/nalgeon/sqlean/releases/0.22.0) (PR #113).
