### ISSUE TITLE
conda support

### ISSUE THREAD

**Issue by axiomofjoy** [nalgeon/sqlean#114]
We are interested in adding `sqlean` as a dependency to our open-source project, but we distribute our package via `conda`, which requires our dependencies to be on conda-forge. Does this package have a conda feedstock?

**Comment by nalgeon** [comment]
Unfortunately, it does not, and I have no idea what conda forge or conda feedstock is.

**Comment by axiomofjoy** [comment]
Thanks for the quick response. Conda forge is a distribution channel for conda, and the feedstock for a repo provides config, instructions for building the package, etc. These are what allow someone to install your package via `conda install`. For example, here's the [feedstock for our project](https://github.com/conda-forge/arize-phoenix-feedstock).

We need to do some more investigation on our end, but we might be interested in adding and maintaining a feedstock for `sqlean` so it can be installed via `conda`. Just wanted to get your initial thoughts here.

**Comment by axiomofjoy** [comment]
Definitely understand. Thanks for your response.
