### ISSUE TITLE
Feature Request: support UUIDv7

### ISSUE THREAD

**Issue by pburrows** [nalgeon/sqlean#116]
Adding support for [UUIDv7](https://datatracker.ietf.org/doc/rfc9562/) would allow sequential, sortable, uuids as PK values in sqlite.

**Comment by nalgeon** [comment]
You are welcome to send a PR.

**Comment by pburrows** [comment]
Tragically, it's been 20 years since I've written anything in C. Perhaps this would be a `good first issue` item?

**Comment by nalgeon** [comment]
I'm afraid it's a little too complex for a first issue.

**Comment by nalgeon** [comment]
I'm not a fan of collecting backlogs, so I'll close this one.

**Comment by nalgeon** [comment]
UUIDv7 implemented in [0.24.0](https://github.com/nalgeon/sqlean/releases/0.24.0)

**Comment by pburrows** [comment]
Thanks so much!
