### ISSUE TITLE
Request to provide precompiled DLLs for x86 Windows

### ISSUE THREAD

**Issue by lucydodo** [nalgeon/sqlean#117]
Hello, I'm @lucydodo, one of the members of the [SQLitebrowser](https://github.com/sqlitebrowser/sqlitebrowser) team. 👋🏻 
We've talked before about including the `sqlean` library in our app bundle: https://github.com/sqlitebrowser/sqlitebrowser/issues/3357

I recently patched the CI workflow in my forked repo to build a `sqlean` DLLs for x86 Windows to include in our project,
and if you're intersted in this, I'd like to make a PR for this upstream repo too. :)

Let me know if you're interested. and I also want to thank you again for this awesome project.
Thank you.

**Comment by nalgeon** [comment]
Hey SeongTae, thanks for your interest in sqlean! You mean a 32-bit Windows version? Sure, you are welcome to send a PR.

**Comment by lucydodo** [comment]
Thanks. I just make a PR: #118

**Comment by nalgeon** [comment]
Huge thanks! Released in [0.23.0](https://github.com/nalgeon/sqlean/releases/0.23.0)
