### ISSUE TITLE
JDBC Driver for SQL IDE

### ISSUE THREAD

**Issue by ryanhamilton** [nalgeon/sqlean#119]
Hi,
I'm the author of qStudio an SQL IDE for data analysts that includes drivers for sqlite: https://www.timestored.com/qstudio/
Currently I embed https://github.com/xerial/sqlite-jdbc but users have raised an issue with REGEXP missing:
https://github.com/timeseries/qstudio/issues/50
If I could get a JDBC driver (with multi-platform support lin/win/mac) that had REGEXP I would bundle it to allow more queries to work.

Would you consider releasing a JDBC driver with REGEXP and other standard calls?

**Comment by nalgeon** [comment]
Hi Ryan! This project is dedicated to C SQLite extensions. I have no plans to release SQLite drivers for Java or any other language.
