### ISSUE TITLE
Make new release to drop "sqlite" prefix

### ISSUE THREAD

**Issue by iainelder** [nalgeon/sqlean#12]
The "sqlite" prefix is dropped from the README, but is still present in the latest release (0.5.0).

https://github.com/nalgeon/sqlean/commit/b9e61df58c1fbfec1b3f51ff96b420bd41b41492

https://github.com/nalgeon/sqlean/releases/tag/0.5.0

This tripped me up just now when trying the library for the first time.

Can you make a new release with the new names?

**Comment by nalgeon** [comment]
I completely forgot about that, sorry. Fixed in [0.6.1](https://github.com/nalgeon/sqlean/releases/tag/0.6.1)
