### ISSUE TITLE
Unicode's hidden `title` function

### ISSUE THREAD

**Issue by christippett** [nalgeon/sqlean#126]
I've been on the lookout for an extension that would allow for converting text to title case. I was intrigued to find that alongside `upper` and `lower` in the unicode library, there's also a `title` function defined (albeit commented out).

I tried compiling the extension with `SQLITE3_UNICODE_TITLE` enabled, however the resulting functionality doesn't work as intended – all it does is convert everything to uppercase (probably why it's commented out!).

I appreciate it's likely to be far down your list of priorities, but is there any chance we might see this functionality resurrected and included in a future `sqlean` release?

**Comment by nalgeon** [comment]
Yes, I plan to review the `unicode` extension and change the underlying implementation to enable the `title` function. Probably later this year.

**Comment by christippett** [comment]
Brilliant! Thanks for the update, I look forward to it.

**Comment by nalgeon** [comment]
As of [0.25.0](https://github.com/nalgeon/sqlean/releases/0.25.0) you can use the `text_title` function from the [text](https://github.com/nalgeon/sqlean/blob/main/docs/text.md) extension:

```sql
select text_title('cómo estás');
-- Cómo Estás
```

Please give it a try.

**Comment by christippett** [comment]
Works well from my limited testing. I added the following two test cases to my local fork, the first passes but the second fails. Other `title()` implementations also don't handle this second case, so it's not unexpected.

```sql
select '27_07', text_title('conan o''brien') = 'Conan O''Brien';
select '27_08', text_title('ronald mcDonald') = 'Ronald McDonald';
```

**Comment by nalgeon** [comment]
Thanks for trying! `text_title` will capitalize the characters on word boundaries and lowercase the rest. In `mcDonald` there is no word boundary before `d`, hence `Mcdonald`.
