### ISSUE TITLE
no such table: generate_series

### ISSUE THREAD

**Issue by iainelder** [nalgeon/sqlean#13]
When I follow the first example in the README, I get an error:

```text
sqlite> .load /opt/sqlean/stats
sqlite> select median(value) from generate_series(1, 100);
Error: no such table: generate_series
```

The median function does work.

```text
sqlite> WITH v(n) AS (VALUES (1), (2), (3), (4)) SELECT median(n) FROM v;
2.5
```

I'm using release 0.6.1.

Is generate_series supposed to behave like [PostgreSQL's function](https://www.postgresql.org/docs/current/functions-srf.html)?

That's what I expected: so the example should return 50.5.

Am I missing something?

**Comment by nalgeon** [comment]
`generate_series()` was built into SQLite shell in version [3.34](https://sqlite.org/releaselog/3_34_0.html). Your version is probably older. You can check the version like this:

```
sqlite> select sqlite_version();
3.35.3
```

**Comment by iainelder** [comment]
Wow, that's awesome, I didn't know SQLite now ships with [generate_series](https://sqlite.org/series.html).

Unfortunately, Ubuntu 20.04 ships with [version 3.31](https://launchpad.net/ubuntu/focal/+source/sqlite3).

```text
$ apt-cache show sqlite3 | ack '^Version:'
Version: 3.31.1-4ubuntu0.2
Version: 3.31.1-4
```

I guess I can get that function by installing the latest [precompiled binary for Linux](https://www.sqlite.org/download.html).

**Comment by nalgeon** [comment]
> I guess I can get that function by installing the latest precompiled binary for Linux.

I tried it, but it didn't work on my Ubuntu 20.04. In case you run into the same problem — use my pre-compiled binary: https://github.com/nalgeon/sqlite/releases/latest

**Comment by iainelder** [comment]
Good to know! I'll try it when I have a moment and let you know.
