### ISSUE TITLE
The 'time' extension is missing from the unifed bundle

### ISSUE THREAD

**Issue by lucydodo** [nalgeon/sqlean#134]
<details>
<summary>Related syntax in the Makefile</summary>

https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L44
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L61
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L78
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L95
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L114
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L129
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L149
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L166
https://github.com/nalgeon/sqlean/blob/92e222525cebe6f1f7d016ee38555d2a3b4a2eea/Makefile#L183\
</details>

The ['time'](https://github.com/nalgeon/sqlean/blob/main/docs/time.md) extension is missing from the single-file `sqlean` bundle.
I know this extension was added 3 weeks ago, is this an intentional behavior to ensure stability?

Thank you :)

**Comment by lucydodo** [comment]
Thanks for quick fix. :)

**Comment by nalgeon** [comment]
Sure, thanks for reporting it!
