### ISSUE TITLE
32 bit version of windows dll?

### ISSUE THREAD

**Issue by cagilla** [nalgeon/sqlean#14]
The sqlite tools package provides only a 32bit windows version of sqlite3.exe.  The currently provided dll's look to be 64 bit.  Is it possible to have a 32 bit precompiled package for windows?

```
SQLite version 3.35.4 2021-04-02 15:20:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .load ./vsv
Error: %1 is not a valid Win32 application.

sqlite>
```

**Comment by nalgeon** [comment]
Nope. But you can use [64-bit sqlite3.exe](https://github.com/nalgeon/sqlite).

**Comment by cagilla** [comment]
great, I did actually try to find a 64 bit version of sqlite3 - and figured it would be harder to get that built.  Your version did not come up in my search.  Perhaps you could make a note on the readme that the dlls are 64 bit and provide your link?  That would have saved a lot of time.

**Comment by nalgeon** [comment]
Thanks, that's a great idea. Mentioned it in the [readme](https://github.com/nalgeon/sqlean/blob/main/README.md).
