### ISSUE TITLE
Missing dependency libgcc_s_dw2-1.dll when using with FireDAC in Windows

### ISSUE THREAD

**Issue by wayneenterprise1** [nalgeon/sqlean#140]
I'm trying to load the mathematical statistics module `stats` from the `sqlean-win-x86.zip` archive (32-bit version) for SQLite database using FireDAC:

`SELECT load_extension('C:\Test\stats');`

But I always get the following error: "The specified module could not be found". The Dependency Walker shows that `libgcc_s_dw2-1.dll` could not be found.

Could you please provide the correct version of this library for Windows as I can't find it? I'm getting the following error: "The specified procedure could not be found".

**Comment by nalgeon** [comment]
Sorry, I don't have a Windows machine and don't have the capacity to investigate the issue.

**Comment by wayneenterprise1** [comment]
What version of GCC/MinGW are you using? Based on this information, I may be able to find a suitable version of the DLL. 30.10.2024, 23:57, "Anton Zhiyanov" ***@***.***>: Sorry, I don't have a Windows machine and don't have the capacity to investigate the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wayneenterprise1** [comment]
What version of GCC/MinGW are you using to build modules in `sqlean-win-x86.zip` archive? Based on this information, I may be able to find a suitable version of the DLL.

**Comment by nalgeon** [comment]
I think it uses [MSYS2](https://www.msys2.org/) ver. 2024-07-27.

**Comment by wayneenterprise1** [comment]
Thank you! However, other extensions from the `sqlean-win-x86.zip` archive that do not have missing modules will also not work in FireDAC: "The specified procedure could not be found". SQLite Studio and DB Browser for SQLite work fine though. Why FireDAC can't work with these extensions is beyond me.
