### ISSUE TITLE
Linux amd64 support

### ISSUE THREAD

**Issue by slavkoja** [nalgeon/sqlean#145]
I decided to try your extensions, and i found, that there are is only Linux x86 file to download. It seems to work, at least it works with your example of ``stat`` extension, but how to be sure?

Please, add amd64 build or specify, if x86 build works for both 32b and 64b systems.

regards

**Comment by nalgeon** [comment]
[sqlean-linux-x86.zip](https://github.com/nalgeon/sqlean/releases/latest/download/sqlean-linux-x86.zip) _is_ the 64-bit build.
