### ISSUE TITLE
Some problems with text extension

### ISSUE THREAD

**Issue by little-brother** [nalgeon/sqlean#15]
1. `split_part` doesn't support non-ansi separator
    ```
    select split_part('привет-ы-мир-ы-привет-мир', 'ы', 2); --> got �иве, but expected: -мир-
    ``` 
2. `split_part` should support a negative part number
    ```
    select split_part('D:/MyDocs/Book1.xls', '/.', -2); --> Book1
    ```
3. Current `text.dll` can't be loaded to sqlite3 cli (Win7 x64, sqlte3cli x32): `Error: Не найден указанный модуль`
    Perhaps, `-static` flag is missed.
4. Use `-s`-flag to reduce dll size.

**Comment by nalgeon** [comment]
> split_part doesn't support non-ansi separator 

Yeah, and it's not going to.

> split_part should support a negative part number 

Maybe in the future.

> Current text.dll can't be loaded to sqlite3 cli (Win7 x64, sqlte3cli x32):

All extensions are 64-bit, they won't work with 32-bit CLI.

> Use -s-flag to reduce dll size.

Thanks, will check that.

**Comment by nalgeon** [comment]
I'm going to close this since I do not plan to change the `text` extension.
