### ISSUE TITLE
win32 extensions

### ISSUE THREAD

**Issue by jgranduel** [nalgeon/sqlean#16]
Hi, 

thanks for this GREAT initiative!
I haven't been able to load Windows dll extension in SQLite3 shell. I installed `sqlite-tools-win32-x86-<version>.zip` for having the console.

```
sqlite> .load ./math
Error: %1 is not a valid Win32 application
```
I tried to compile with gcc and cl on my own side without success (I'm not proficient in C and less on Windows C toolchain)
```
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat
> cl.exe sqlite3-math.c -link -dll "-out:sqlite3-math.dll"
sqlite3> .load ./sqlite3-math
Error: %1 is not a valid win32 application
```
Same result with gcc (`gcc.exe -s -O3 -m32 -c -g -shared ./sqlite3-math.c -o ./sqlite3-math.dll`). Compiles but cannot load.
Any help on my mistake?

**Comment by nalgeon** [comment]
Hi there! Thanks for trying sqlean! Binaries are 64-bit and require a 64-bit SQLite version. If you are using SQLite shell on Windows (sqlite.exe), its 64-bit version is available at https://github.com/nalgeon/sqlite. The 32-bit shell (downloaded from https://sqlite.org/download.html) won't do.

**Comment by jgranduel** [comment]
Thank you very much. 
I cann't believe I hadn't seen the paragraph in the README **"Binaries are 64-bit and require a 64-bit SQLite version. If you are using SQLite shell on Windows (sqlite.exe), its 64-bit version is available at https://github.com/nalgeon/sqlite."**!
I don't know why the 64-bit version is not available on SQLite site for the shell by the way.

Hope other extensions can be hosted over here !👍

**Comment by nalgeon** [comment]
Glad that you've sorted that out!

> I don't know why the 64-bit version is not available on SQLite site for the shell by the way.

This remains a mystery to me either ツ

Let me know if there is a specific extension you need — I'll gladly take a look.
