### ISSUE TITLE
Question about crypto extension

### ISSUE THREAD

**Issue by jgranduel** [nalgeon/sqlean#17]
Hi, 

not a real issue, rather a question (SQLite-3.36.0).

I tried using `crypto` to hash some file paths automatically, but it doesn't seem possible to use it likewise in generated columns:
```
sqlite> create table t(pth, sha generated always as (hex(sha256(pth))) stored);  -- or any md5, sha384, or sha512 functions of course
Error: non-deterministic functions prohibited in generated columns
```
I thought hashing functions were determisitic ([see](https://crypto.stackexchange.com/questions/29650/sha-256-almost-unique)). Why is that?
Using `SQLITE_DETERMINISTIC` ([https://www.sqlite.org/deterministic.html](https://www.sqlite.org/deterministic.html)) should be used at compile time of the extension, right?

Thanks for any tip if ever you happen to have time!

**Comment by nalgeon** [comment]
Sure, hashing functions are deterministic. Thanks for the bug report! Fixed in [0.8.2](https://github.com/nalgeon/sqlean/releases/tag/0.8.2)
