### ISSUE TITLE
[QUESTION] Node npm wrapper

### ISSUE THREAD

**Issue by zbubric** [nalgeon/sqlean#24]
Hi guys,

first of all, I would to thank you for this lib. It really saved my day(s) when I needed to calculate median on group results :)
I used it on a nodejs project on (a bit) primitive way: adding your precompiled binary into my source code and loading it via [sqlite3 nodejs module](https://www.npmjs.com/package/sqlite3). I came to idea to pack them into npm module to ease usage for other NodeJs developers (at least those that are not so eager to build it from source, like me :) ).
I just wanted to check with you are you ok with that idea? Off-course, If I do it, I plan to reference your original repo from readme of node wrapper project?

BR
Zoran

**Comment by nalgeon** [comment]
Hello Zoran! Thanks a lot! Sure, feel free to create an npm package if you find it useful.

**Comment by zbubric** [comment]
Hi @nalgeon,

node/npm wrapper is availabel at https://github.com/zbubric/sqlite3-sqlean
