### ISSUE TITLE
Missing stats percentile functions

### ISSUE THREAD

**Issue by Alain2019** [nalgeon/sqlean#26]
Hi

Could it be possible to add the symmetric percentile functions : 01, 05 and 10 (same logic as  90,95 and 99)?

Or even better a percentile function where the percentile is a parameter.

**Comment by nalgeon** [comment]
I've just added `percentile(x, perc)` function in release [0.14.0](https://github.com/nalgeon/sqlean/releases/tag/0.14.0).
