### ISSUE TITLE
JSON1

### ISSUE THREAD

**Issue by CompuRoot** [nalgeon/sqlean#30]
Hello,

In the latest release [0.15.1][1], on the top you stated with message:
> json1 extension in SQLite 3.37 is buggy, switched to 3.36.

I tried to find the case but failed, could you please point to the bug in `JSON1` ?

[1]: https://github.com/nalgeon/sqlean/releases/tag/0.15.1

**Comment by nalgeon** [comment]
Hey there! See this thread: https://sqlite.org/forum/info/858dee399ec0d982

**Comment by CompuRoot** [comment]
Ohh, I see, thank you.

Why then not to use Richard's suggestion to just compile with `NDEBUG` flag instead of missing recent changes in 3.37 branch ?

```
gcc -fPIC -shared -DNDEBUG json1.c -o json1.so
```

**Comment by nalgeon** [comment]
Because there are no functional changes to JSON1 in 3.37.

**Comment by CompuRoot** [comment]
Im lost, sorry, why then state that **"json1 extension in SQLite 3.37 is buggy, switched to 3.36"**
if  **"there are no functional changes to JSON1 in 3.37"**.

**Comment by nalgeon** [comment]
3.37 brings no new features to JSON1, but breaks its functionality. Therefore, there is no profit in using 3.37.
