### ISSUE TITLE
Extension that supports Protocol buffers

### ISSUE THREAD

**Issue by CompuRoot** [nalgeon/sqlean#32]
[Here is][1] extension that implements [Protocol Buffers][2] that you might want to add to the existing set of extensions 

[1]: https://github.com/rgov/sqlite_protobuf
[2]: https://developers.google.com/protocol-buffers

**Comment by nalgeon** [comment]
sqlean focuses on extensions with little to no external dependencies. This one requires Google's Protobuf, which is quite huge. So currently it's clearly out of scope.
