### ISSUE TITLE
SQLite-parquet-vtable extension

### ISSUE THREAD

**Issue by jgranduel** [nalgeon/sqlean#33]
Hi, 

thanks for your project again, and the incubator parts!
I've come across this extension for reading Apache parquet files [sqlite-parquet-vtable](https://github.com/cldellow/sqlite-parquet-vtable) which could be an incubator candidate, if license and author allows for it. There's no release of it apart from source.

best regards

**Comment by nalgeon** [comment]
Hello there! Thank you for your interest ツ The parquet extension looks great, but it has a lot of external dependencies. `sqlean` scope is currently limited to extensions without dependencies. Citing the readme:

> We want every extension to be self-contained. So we limit the project scope to extensions without external dependencies (other than the C standard library and SQLite itself).

We may extend the scope later, but not before we deal with existing extensions first.

**Comment by jgranduel** [comment]
Perfect choice of course! I had overlooked the readme. Thanks

**Comment by nalgeon** [comment]
Sure 🙏 I'll reopen the issue if we decide to extend the project scope.
