### ISSUE TITLE
How to override existing functions with extension

### ISSUE THREAD

**Issue by cherman82** [nalgeon/sqlean#36]
I'm using unicode.dll with mine sqlite engine as loadable extension.
nlower() function works as it suppose to, but lower() still does not lowercase unicode strings.

I guess lower() still uses original implementation.
How to make lower to use implementation provided by extension?

**Comment by cherman82** [comment]
Acctually I've tested CLI from here:
https://github.com/nalgeon/sqlite/releases/latest

with load_extension:
![image](https://user-images.githubusercontent.com/102728775/161030438-076ca61e-61a4-4c91-a0c6-b7008a01ff90.png)

with .load:
![image](https://user-images.githubusercontent.com/102728775/161030563-054bdc9f-3ce4-476a-8d18-8dbf1de3c75c.png)


As you can see load_extension does not override lower function.

**Comment by cherman82** [comment]
load_extension provides new function nupper, but does not override upper function.

![image](https://user-images.githubusercontent.com/102728775/161031446-9e811dc8-aa18-43a3-98ae-f59457b5a558.png)

**Comment by nalgeon** [comment]
That's right, `load_extension()` does not provide the means to override existing functions due to SQLite restrictions. Quoting the [docs](https://sqlite.org/lang_corefunc.html#load_extension):

> The load_extension() function will fail if the extension attempts to modify or delete an SQL function or collating sequence. The extension can add new functions or collating sequences, but cannot modify or delete existing functions or collating sequences because those functions and/or collating sequences might be used elsewhere in the currently running SQL statement. To load an extension that changes or deletes functions or collating sequences, use the `sqlite3_load_extension()` C-language API.

**Comment by drhsqlite** [comment]
To clarify:  The quoted documentation refers to the `load_extension()` SQL function.  It is true because SQLite does not allow functions to be overloaded while an SQL statement (that might be using that functions) is running.  However, the `sqlite3_load_extension()` C-language interface is able to overload functions.  The "`.load`" command of the CLI uses the `sqlite3_load_extension()` C interface, so it is able to load extensions that overload functions.

**Comment by nalgeon** [comment]
Absolutely. @cherman82 uses `load_extension()` SQL function to load the `unicode` extension, so it fails to override the `upper()` function. If one uses `.load` command to load the `unicode` extension, it overloads the `upper()` function just fine.

**Comment by cherman82** [comment]
@nalgeon @drhsqlite i'm affraid you are both wrong.
unicode.c tries to overload lower (and upper) function which has one parameter with oncoding of SQLITE_ANY, and in meantime original functions has one parameter with encoding SQLITE_UTF16|SQLITE_DETERMINISTIC|SQLITE_INNOCUOUS.
If you create a function which parameter has correct encoding then everything works even using load_extension:

![image](https://user-images.githubusercontent.com/102728775/161475979-29cb2d57-5925-4fbd-912d-726521fbe413.png)

**Comment by drhsqlite** [comment]
I think it tries to pick the one that involves the least amount of conversion work.  So if it is picking the SQLITE_UTF16 implementation, that implies that the content it is trying to operate on is also UTF16.
