### ISSUE TITLE
[Feature Request] math.dylib extension compiled for ARM64

### ISSUE THREAD

**Issue by vpoguru** [nalgeon/sqlean#40]
Any chance to get the math.dylib extension work on Macs with Apple Silicon chip?

**Comment by nalgeon** [comment]
I haven't figured an automated way to build macos arm64 extensions, so I built them manually for now: <https://github.com/nalgeon/sqlean/releases/tag/0.15.2>

Or you can just use SQLite 3.35+

**Comment by vpoguru** [comment]
Unfortunately, there are still a few math functions missing in the tool I use: https://github.com/xerial/sqlite-jdbc/issues/633

I needed log2(X) and power(X,Y). Your extension works with charm! Many thanks!

**Comment by nalgeon** [comment]
Sure!

**Comment by diekhans** [comment]
you should be able to build universal modules with xcode:

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
