### ISSUE TITLE
PostScript tokens out

### ISSUE THREAD

**Issue by zzo38** [nalgeon/sqlean#42]
Here is a extension for making PostScript tokens (public domain):

jar:http://www.dessus.com/files/sqlite3extensions.zip!/pstoken.c

Note, that PostScript does not distinguish text/blobs; they are the same type in PostScript. However, this extension uses a different syntax for them.

**Comment by nalgeon** [comment]
Nobody showed any interest in this extension, so I'm going to close the issue.
