### ISSUE TITLE
Cannot use .*? in regexp_replace

### ISSUE THREAD

**Issue by LaurentDhont** [nalgeon/sqlean#43]
When using .*? in regexp_replace it fails with regexp(3): nested *?.

**Comment by nalgeon** [comment]
This extension does not support lazy quantifiers, and I have no plans to add it.

**Comment by nalgeon** [comment]
Lazy quantifiers are supported in the [regexp](https://github.com/nalgeon/sqlean/blob/main/docs/regexp.md) extension starting with the [0.18](https://github.com/nalgeon/sqlean/releases/tag/0.18.2) release:

```sql
sqlite> select regexp_substr('brave new world', '.*e');
brave ne

sqlite> select regexp_substr('brave new world', '.*?e');
brave
```
