### ISSUE TITLE
Non-Unicode SQLite

### ISSUE THREAD

**Issue by zzo38** [nalgeon/sqlean#44]
Would patches to SQLite be possible, too? Many things are possible by extensions but some things may need patching the code of SQLite itself, too, or are working better by patches. One patch is below but others are also possible too.

I made up a patch to improve SQLite by excluding the Unicode capabilities. (Hopefully can also be tested if combined with other patches too.)

- [Non-unicode patch](http://sprunge.us/OS1s6s)

- [Program to apply patches](http://sprunge.us/GYJV5V)

- [Fossil repository with patches](http://zzo38computer.org/fossil/sqlitepatches.ui/dir?ci=tip)

**Comment by zzo38** [comment]
The insistence of using Unicode is a design flaw; that is why I implemented a patch to try to avoid the use of Unicode as much as possible. I think that `%!s` is not actually that useful anyways, but it is kept in there for compatibility purpose, since it does not interfere with the attempt to use non-Unicode text (you can use `%s` instead). (I may change this to remove this Unicode capability too, but currently it isn't.)

**Comment by nalgeon** [comment]
Sorry, I have no plans to patch SQLite. This project is dedicated to extensions.

**Comment by zzo38** [comment]
OK, that is reasonably enough. (I have my own repository for patches, and would like to see others contribute proposals and patches and other information there, too. I have started writing and intend to soon commit some changes with some further documents, too. I may also add extensions as well as patches in future, too.)
