### ISSUE TITLE
Regexp functions flagged as not deterministic

### ISSUE THREAD

**Issue by RDelg** [nalgeon/sqlean#46]
Hello,
I am wondering why the regexp functions are not flagged with `SQLITE_INNOCUOUS` and `SQLITE_DETERMINISTIC`.
It is giving me an error when trying to use regexp_replace in a generated column.

```bash
sqlite> .load ./re
sqlite> create table test as select "name" as name;
sqlite> alter table test add column new_name generated always as (regexp_replace(name,'.','N'));
Runtime error: error in table test after add column: non-deterministic functions prohibited in generated columns
```

**Comment by nalgeon** [comment]
Marked functions as deterministic in [0.15.3](https://github.com/nalgeon/sqlean/releases/tag/0.15.3).
