### ISSUE TITLE
regex syntax missing

### ISSUE THREAD

**Issue by chris-dailey** [nalgeon/sqlean#49]
I've been using the [regexp](https://sqlite.org/src/file/ext/misc/regexp.c) extension prior to finding the `re` extension here.  The `regexp` extension only implements the `REGEXP` statement but includes additional syntax.  Would it be possible to update `re` to support the same syntax?

```
X*      zero or more occurrences of X
X+      one or more occurrences of X
X?      zero or one occurrences of X
X{p,q}  between p and q occurrences of X
(X)     match X
X|Y     X or Y
^X      X occurring at the beginning of the string
X$      X occurring at the end of the string
.       Match any single character
\c      Character c where c is one of \{}()[]|*+?.
\c      C-language escapes for c in afnrtv.  ex: \t or \n
\uXXXX  Where XXXX is exactly 4 hex digits, unicode value XXXX
\xXX    Where XX is exactly 2 hex digits, unicode value XX
[abc]   Any single character from the set abc
[^abc]  Any single character not in the set abc
[a-z]   Any single character in the range a-z
[^a-z]  Any single character not in the range a-z
\b      Word boundary
\w      Word character.  [A-Za-z0-9_]
\W      Non-word character
\d      Digit
\D      Non-digit
\s      Whitespace character
\S      Non-whitespace character
```

**Comment by nalgeon** [comment]
Not in the near future, I'm afraid. Not ready to bury myself in the regexp engine internals.

**Comment by chris-dailey** [comment]
Understood and thank you for the quick response.  I had hoped the linked code for the other module could be ported without much extra effort.

**Comment by nalgeon** [comment]
Unfortunately, it could not. I've considered the regexp extension earlier, and found it not suited for substr and replace operations. So the re extension is built on a completely different engine.

**Comment by drjdpowell** [comment]
Would not at least some of these be relatively easy?

> **     \b      Word boundary
> **     \w      Word character.  [A-Za-z0-9_]
> **     \W      Non-word character
> **     \d      Digit
> **     \D      Non-digit
> **     \s      Whitespace character
> **     \S      Non-whitespace character

Like the \w just gets replaced with [A-Za-z0-9_], \d with [0-9], etc.  If not easy, then I understand.

**Comment by nalgeon** [comment]
Not really. Sorry. I'll look into switching the current regexp engine to something more powerful, but the last time I checked, there wasn't one suitable for this project.

**Comment by nalgeon** [comment]
The new [regexp](https://github.com/nalgeon/sqlean/blob/main/docs/regexp.md) extension in [0.18.0](https://github.com/nalgeon/sqlean/releases/tag/0.18.0) provides much more advanced syntax. Unfortunately, it does not support Windows at the time.

**Comment by nalgeon** [comment]
Implemented the new `regexp` extension for Windows in [0.18.1](https://github.com/nalgeon/sqlean/releases/tag/0.18.1).

**Comment by chris-dailey** [comment]
Thank you very much for adding this extension.  I'm thrilled to have the additional syntax available now.
