### ISSUE TITLE
[array: unnest] crash & no solution

### ISSUE THREAD

**Issue by Moaneschien** [nalgeon/sqlean#52]
```
SELECT value 
FROM unnest(array(0,1,2,3,4,5))
WHERE value < 3;
```
> Parse error: no query solution 
(not sure what the behavior should be. I hoped for an other result)

```
SELECT value
FROM unnest (1);
```
> crashes SQLite without error

**Comment by nalgeon** [comment]
This one took some time 😅 Fixed now.

The first one returns three rows:

```sql
SELECT value 
FROM unnest(array(0,1,2,3,4,5))
WHERE value < 3;
```

```
0
1
2
```

The second one returns an error, because the argument to `unnest` is not a valid array:

```sql
SELECT value
FROM unnest(1);
```

```
Runtime error: SQL logic error
```
