### ISSUE TITLE
Add fts5-snowball extension to support many languages in full text search

### ISSUE THREAD

**Issue by and-se** [nalgeon/sqlean#6]
Sqlite supports full-text search with `fts5` extension, but out of the box there is only english tokenizer.

[fts5-snowball](https://github.com/abiliojr/fts5-snowball) extension adds support for the snowball stemmer for a variety of languages, which could serve as a good addition to the `sqlite3unicode` module.

Look at [this PR](https://github.com/abiliojr/fts5-snowball/pull/8), which fixes some crashes and adds support to sqlite < 3.20.0 (at this release fts5 extension api slightly changed).

**Comment by nalgeon** [comment]
While snowball is a great library, it's a solid external dependency. We are currently explicitly limiting this project to [extensions with zero dependencies](https://github.com/nalgeon/sqlean#contributing), so I'm going to close the issue for now. Will reopen later if we expand the scope.
