### ISSUE TITLE
Date functions which take into account leap years and seconds

### ISSUE THREAD

**Issue by Mythli** [nalgeon/sqlean#62]
Dear sqlean team,

working with sqlite dates is a real pain because date modifiers don't take into account leap years making the output of them unreliable.

The users of my app would consider this a serious bug.

Example:

```sql
select datetime('1993-06-30 23:59', '+20 months') as dt;
```

should return `1995-02-28 23:59` but it returns `1995-03-02 23:59:00` because sqlite does not take into account leap years.

1. Do you know of any plugin with proper date and time functions which work bug free?
2. If not, do you know any hack which can solve this?

I believe a plugin for better date and time handling including convenience functions for formatting, parsing and modifying dates would very much help the community.

Best regards

**Comment by nalgeon** [comment]
The problem isn't in leap years, I believe. For example, this query in SQLite:

```sql
select datetime('1993-08-31', '+1 month') as dt;
```

returns `1993-10-01`.

While the same query in PostgreSQL (or MySQL):

```sql
select '1993-08-31'::date + interval '1 month';
```

returns `1993-09-30`.

I don't know how to make SQLite behave like PostgreSQL in this case, unfortunately.

**Comment by nalgeon** [comment]
Sorry, I have no plans to add new features at this time.
