### ISSUE TITLE
pivotvtab fails on M1 Pro MacBook

### ISSUE THREAD

**Issue by punkish** [nalgeon/sqlean#65]
The `pivotvtab` extenstion fails on M1 Pro MacBook.

**Comment by punkish** [comment]
The macos version fails on M1 Pro MacBook with the error (exact copy and paste below)

```
Error: dlopen(../../bin/sqlite-exts/pivotvtab.dylib, 0x000A): tried: '../../bin/sqlite-exts/pivotvtab.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS../../bin/sqlite-exts/pivotvtab.dylib' (no such file), '/usr/lib/../../bin/sqlite-exts/pivotvtab.dylib' (no
```

**Comment by nalgeon** [comment]
Yeah, it wasn't compiled for M1. You can [re-download](https://github.com/nalgeon/sqlean/releases/download/incubator/pivotvtab.dylib) it now, and it will work (after you overcome the macOS refusal to launch it due to security reasons).

Be aware, though, that this extension is buggy and may fail with 'segmentation fault' errors.

**Comment by punkish** [comment]
yes, you are correct. Sadly I got the segmentation fault :(

**Comment by punkish** [comment]
> If the number of years in your table is limited (say, five years like in your example)

Unfortunately no :(. As I mentioned in  my message on the [SQLite forums](https://sqlite.org/forum/forumpost/ec90cc1429), I have 173 years, and over time this will only grow. I have to be able to do this programmatically.

**Comment by nalgeon** [comment]
Then I'd construct the query dynamically and use Python or another language to execute it.

**Comment by nalgeon** [comment]
You even can construct the query from SQL like this:

```sql
with years as (
  select distinct(y) as year
  from t
),
lines as (
  select 'select j' as cond
  union all
  select ',count(y) filter (where y = ' || year || ') as "' || year || '" '
  from years
  union all
  select 'from t group by j;'
)
select group_concat(cond, '') as v
from lines;
```

Result:

```sql
select j,count(y) filter (where y = 1990) as "1990" ,count(y) filter (where y = 1991) as "1991" ,count(y) filter (where y = 1992) as "1992" ,count(y) filter (where y = 1994) as "1994" ,count(y) filter (where y = 1993) as "1993" from t group by j;
```

But then you'd have to execute this constructed query, and SQLite can't do that, to my knowledge.

**Comment by punkish** [comment]
yea, I will try to do it programmatically as you suggested (I use nodejs and it is easy for me to construct the query there). Not really what I desired as I wanted a db-solution (rather than a program solution) that would update the count frequency table via triggers, but hey, as long as it works :)

Thanks for your help.

By the way, thanks also for all these wonderful extensions.

**Comment by punkish** [comment]
ha ha, I spoke too soon. I built the query but got the following error

```
SqliteError: too many columns in result set
```

I guess I just have to look at some other way of solving this.

**Comment by punkish** [comment]
>> too many columns in result set

> That's strange, I was pretty sure that [max column limit](https://www.sqlite.org/limits.html#max_column) is 2000 by default.

It was my error, I made a mistake. Fixed that and it is working now. Now I have to figure out how to automate this, but this is a great help. Many thanks.

**Comment by nalgeon** [comment]
Ah! I've figured it out. We can execute a dynamic query using the `eval` function from the [define](https://github.com/nalgeon/sqlean/blob/main/docs/define.md) extension.

For example, we can create a view (or table) named `vt`, which will return the required pivoted data:

```sql
with years as (
  select distinct(y) as year
  from t
),
lines as (
  select 'create view vt as ' as part
  union all
  select 'select j '
  union all
  select ',count(y) filter (where y = ' || year || ') as "' || year || '" '
  from years
  union all
  select 'from t group by j;'
)
select eval(group_concat(part, ''))
from lines;
```

And work with it afterwards:

```sql
select * from vt;
```

```
┌─────┬──────┬──────┬──────┬──────┬──────┐
│  j  │ 1990 │ 1991 │ 1992 │ 1994 │ 1993 │
├─────┼──────┼──────┼──────┼──────┼──────┤
│ bar │ 2    │ 0    │ 0    │ 0    │ 1    │
│ baz │ 1    │ 1    │ 1    │ 0    │ 0    │
│ foo │ 1    │ 3    │ 1    │ 1    │ 0    │
└─────┴──────┴──────┴──────┴──────┴──────┘
```
