### ISSUE TITLE
Python packages for sqlean extensions

### ISSUE THREAD

**Issue by karlb** [nalgeon/sqlean#66]
When using SQLite extensions from python in the past, I made python packages out of them (e.g. https://github.com/karlb/sqlite-spellfix) so that I could specify them properly as dependencies and not worry too much about getting the right extension for the current platform.

Did someone do something similar for the sqlean extensions? If not, are there expectations on how that should be done? 

Potential questions:
* Is there demand for this at all?
* Should this be part of sqlean or managed separately?
* Would the simplicity of a single package be preferred or the granularity of one-package-per-extension?
* Would it be important to provide binaries for many platforms or can we assume the presence of a C-compiler?
* Any volunteers to contribute to such a solution?

**Comment by nalgeon** [comment]
Hello Karl! As far as I remember, nobody asked for pip packages. But after reading the recent [Making SQLite extensions pip install-able](https://observablehq.com/@asg017/making-sqlite-extensions-pip-install-able) article, I think we can still do it.

I like the approach Alex took (see [sqlite_regex](https://github.com/asg017/sqlite-regex/tree/main/python/sqlite_regex)), where setup.py downloads the pre-compiled binaries, so no compiler is needed.

For `sqlean`, it makes sense to release a single `sqlean` package that provides access to all extensions from the main set. There is no reason for pip-installing the incubator extensions, though.

It should probably be a separate repo to keep things clean and simple.

Unfortunately, the `sqlean` package name is already taken in PyPI. I asked the author if they would agree to transfer it.

**Comment by diekhans** [comment]
pip install support would be fantastic.  Happy to help test

**Comment by karlb** [comment]
I'll give it a try and let you know when there is a first working version.

**Comment by nalgeon** [comment]
Note: you don't need the sqlean sources. There are [precompiled binaries](https://github.com/nalgeon/sqlean/releases/latest) for every OS; the python package can use them.

**Comment by karlb** [comment]
> Note: you don't need the sqlean sources. There are [precompiled binaries](https://github.com/nalgeon/sqlean/releases/latest) for every OS; the python package can use them.

Yes, I just went with what I have done before for the very first version. Both approaches have they advantages.

Source based:
* Can be installed on systems without pre-built binaries (e.g. linux-arm). Note: This does not mean that most users will need a C compiler, since we can still upload binary wheels to PyPI
* More similar to typical python extensions (not sure if that has any practical advantages, though)
* Can use common infrastructure such as https://cibuildwheel.readthedocs.io to build and test for many platforms (probably only a real advantages for those platforms without official sqlean binary releases)

Binary based:
* Exactly the same extension binaries and thus better tested builds
* Less duplication of build system (and thus probaby less maintenance burden)

I might just give Alex' binary download approach a try next to get a better feel for it. In any way, it is a nice to have a first version which passes the tests to compare against.

**Comment by karlb** [comment]
@diekhans If you like the source based approach, you can already try https://github.com/karlb/sqlite-sqlean. From what I can see it works, but I have not tried it out in a real project yet. I didn't upload to PyPI yet, since it is still unclear whether we will be able to use the "sqlean" package name or not. I have chosen then name "sqlite-sqlean" for the meantime.

**Comment by diekhans** [comment]
thanks!  I tried direct install from github and get the following error:

    % pip install git+git://github.com/karlb/sqlite-sqlean
    Collecting git+git://github.com/karlb/sqlite-sqlean
      Cloning git://github.com/karlb/sqlite-sqlean to /private/var/folders/3k/fvyxn7p97976wmlmtkd7ltfr0000z8/T/pip-req-build-_68ghnjr
      Running command git clone --filter=blob:none --quiet git://github.com/karlb/sqlite-sqlean /private/var/folders/3k/fvyxn7p97976wmlmtkd7ltfr0000z8/T/pip-req-build-_68ghnjr
      fatal: unable to connect to github.com:
      github.com[0: 192.30.255.112]: errno=Operation timed out

      error: subprocess-exited-with-error

      × git clone --filter=blob:none --quiet git://github.com/karlb/sqlite-sqlean /private/var/folders/3k/fvyxn7p97976wmlmtkd7ltfr0000z8/T/pip-req-build-_68ghnjr did not run successfully.
      │ exit code: 128
      ╰─> See above for output.


This happens and can be repeated on two different machines (Mac
M1 and Linux) on different networks.

Pushing to my own github repos work great.

I think sqlite-sqlean is a great name!

**Comment by karlb** [comment]
>     % pip install git+git://github.com/karlb/sqlite-sqlean

Ah, yes. I need to update the docs, since github turned off access over `git://`. Use `pip install git+https://github.com/karlb/sqlite-sqlean`, instead.

**Comment by karlb** [comment]
Should we close this issue and rather add new issues to https://github.com/karlb/sqlite-sqlean/issues?

**Comment by diekhans** [comment]
Yes, close. will add issues there.
