### ISSUE TITLE
Wishing for Row->JSON-Object conversion

### ISSUE THREAD

**Issue by Asc2011** [nalgeon/sqlean#67]
Hi evbr,

in the Sqlite-CLI-tool, one can :
```
.mode json
SELECT * FROM MyTable;
.mode table
```
and every row will be returned as a JSON-Object.
That is quite handy and has been discussed in the Sqlite-Forums. There is no SQL-solution where one can use a '*' to select all row-members. 
I'd really appreciate a extension, that would allow to do this, without 3rd-party scripting.

best regards,

**Comment by nalgeon** [comment]
I've given it some thought, but still have no idea how to implement it. I will close the issue for now; please let me know if you see a possible implementation.
