### ISSUE TITLE
Q: Way to static link all these into a single library?

### ISSUE THREAD

**Issue by jay-swyfft** [nalgeon/sqlean#69]
Is it possible to link some subset of these into a static library to be included directly in a binary?

**Comment by nalgeon** [comment]
Do you mean compiling all extensions into the SQLite binary itself? It's possible, but may require some code changes. And I've never tried it.

**Comment by jay-swyfft** [comment]
Yes. I imagine that this would be easier for mobile platforms and other constrained environments.

BTW, this is a really great resource. Thanks for putting it together.

**Comment by nalgeon** [comment]
I've thought about bundling with SQLite, but haven't tried it yet. Will do someday.

Thanks a lot!

**Comment by nalgeon** [comment]
The first step is a single-file extension bundle, available as of [0.21.0](https://github.com/nalgeon/sqlean/releases/0.21.0).

**Comment by nalgeon** [comment]
The second step is a [custom SQLite shell](https://github.com/nalgeon/sqlite/releases/3.42.0-sqlean) with preinstalled extensions.

**Comment by nalgeon** [comment]
The third step is a [drop-in replacement](https://github.com/nalgeon/sqlean.py) for Python's `sqlite3` module.

**Comment by nalgeon** [comment]
The fourth (and probably final) step is the [browser-based build](https://github.com/nalgeon/sqlean.js). Let me know if you have something else in mind.
