### ISSUE TITLE
Parquet vtable extension

### ISSUE THREAD

**Issue by holajoyce** [nalgeon/sqlean#7]
Hello, thank you for this repo!  I've been trying to compile the following library, but having no success, if you guys are able to compile and include in this repo, that would be wonderful.

https://github.com/cldellow/sqlite-parquet-vtable/

**Comment by nalgeon** [comment]
Hello Joyce! My current rule is to include only extensions without third party dependencies, and sql-parquet-vtable has a lot of those.

What kind of problems have you encountered while compiling the extension? It has a makefile, so at first glance, everything should be fine.
