### ISSUE TITLE
wasm module

### ISSUE THREAD

**Issue by alexbodn** [nalgeon/sqlean#77]
hello andrey and thank you very much for extending sqlite.
i'm particularly interested in the define module, since i'd like one db to be shared in python and js.
sqlite is a powerful sql to go, and now browsers and phones can put very powerful environments in your pocket.
i'd ask you to provide the modules as wasm, for use in the browser.

hope it's not a too heavy challenge.

**Comment by nalgeon** [comment]
Unfortunately, I have no idea how to make WASM extensions and how to make SQLite WASM build load them.

**Comment by silver5753** [comment]
I'm not sure WASM is mature enough for dynamic shared library loading, but I might be wrong.
In any case, the official SQLite WASM version (which is available to try on sqlime, another great project) has extension loading disabled. 
Select * from pragma_compile_options:
OMIT_LOAD_EXTENSION

**Comment by alexbodn** [comment]
indeed would be interesting to dynamically load the modules, but if we
don't know to do it, they may also be statically linked, if i
understand correctly.
i never compiled anything to wasm, that's why i asked it here.

alex

**Comment by alexbodn** [comment]
today i came across this wonderful module.
if we could wasm it, sqlime would greatly benefit from it.

https://github.com/aergoio/sqlite-stored-procedures

what do you think?

alex

**Comment by nalgeon** [comment]
WASM build: https://github.com/nalgeon/sqlean.js

**Comment by DBJDBJ** [comment]
1. WASI 
2. Look into Docker efforts

Sorry for brevity
