### ISSUE TITLE
Feature request: a Base32/64 (en/de)coder for 'crypto'

### ISSUE THREAD

**Issue by veermans** [nalgeon/sqlean#78]
Thanks for the very rich SQLite extension set!

It would be great to have a base32 (and base64) converter (encoding and decoding) with the 'crypto' extension as an alternative to the hex function for producing output of the SHA functions that is both readable and as compact as possible ([rfc4648](https://datatracker.ietf.org/doc/html/rfc4648)). The filename-safe alternative (64) and the extended-hex alternative (32) might also fit some use cases.

Best, Erwin

**Comment by nalgeon** [comment]
Working on it.

**Comment by asg017** [comment]
btw in case you haven't seen, the SQLite team recently added these to their codebase, in case you want to adopt it 

https://sqlite.org/src/file?name=ext/misc/base64.c

https://sqlite.org/src/file?name=ext/misc/base85.c

https://sqlite.org/src/file?name=ext/misc/basexx.c

**Comment by nalgeon** [comment]
Added `encode` and `decode` functions in [0.19.14](https://github.com/nalgeon/sqlean/releases/0.19.4):

```sql
select encode('hello', 'base32');
-- NBSWY3DP
select decode('NBSWY3DP', 'base32');
-- hello
```

```sql
select encode('hello', 'base64');
-- aGVsbG8=
select decode('aGVsbG8=', 'base64');
-- hello
```

@veermans please let me know if they fit your use cases.

**Comment by veermans** [comment]
Yes, works like a charm. Thanks!

**Comment by nalgeon** [comment]
Added three more algorithms — `base85`, `hex` and `url` — in [0.19.5](https://github.com/nalgeon/sqlean/releases/tag/0.19.5). I think that's enough for now.
