### ISSUE TITLE
Amalgamation build

### ISSUE THREAD

**Issue by Dialga** [nalgeon/sqlean#79]
Just an idea for consideration, have you considered making an amalgamated build of the sqlite with all the extensions baked in? That would make it much more accessible for end users to get up and running with all the benefits of the extra functions this repo provides, into one executable akin to busybox for SQLite.

**Comment by nalgeon** [comment]
I've considered it (see #69), but haven't had the time yet. Fingers crossed, sometime this year.

**Comment by nalgeon** [comment]
I'm going to close this issue as duplicate and track the progress in #69.
