### ISSUE TITLE
Call for Feedback

### ISSUE THREAD

**Issue by nalgeon** [nalgeon/sqlean#81]
If you find `sqlean` useful in your work or personal projects — I'd love to know more about your use cases. It will really help me to focus on the most important aspects and not waste time on things nobody cares about.

So if you'd like to help this project, please answer the following 3 questions in the comments:

1. What is your role in the organization? (e.g. "I'm a mobile app developer" or "I'm a data analyst")
2. What do you use `sqlean` for? (e.g. "To work with Unicode data in the app" or "For math statistics in financial reports")
3. What is the top 1 thing you miss in `sqlean`? (e.g. "An extension for working with dates" or "A Python package")

If you'd rather answer privately — drop me a line at m@antonz.org

Thank you for your support!

**Comment by jepiqueau** [comment]
Is there a precompiled binaries for Android (Java or Kotlin)?

**Comment by edgarrmondragon** [comment]
Hi Anton 👋.

1. Software Engineer
2. We maintain a CLI that uses a database (via [SQLAlchemy](https://www.sqlalchemy.org/)) to store job execution history and data sync state.

   I'm experimenting with shipping our application with its own SQLite binary dependency to avoid problems where users install the application in an environment with an older version of SQLite (e.g. EC2) that are missing key features, such as `ALTER TABLE ... RENAME ... TO`. One workaround is to use `pysqlite3`, but the binary package (`pysqlite3-binary`) only has wheels for Linux, so at best Windows and MacOS users would have to build their own wheels.

  This is where `sqlean.py` would come to save the day by having more wheels available, allowing us to ship an application users can install without needing to build any wheels on their end.

3. PyPI wheels for [`0.21.5.2`](https://github.com/nalgeon/sqlean.py/releases/tag/0.21.5.2) 😅

Thanks for creating `sqlean` and `sqlean.py`!

**Comment by nalgeon** [comment]
Edgar, thank you for the feedback! (also for the PR) I screwed up the 0.21.5.2 release, but now, thanks to you, the [0.21.5.3](https://pypi.org/project/sqlean.py/0.21.5.3/) should be published.

**Comment by fractaledmind** [comment]
* What is your role in the organization?
I'm the head of engineering at my day job and a freelance Rails developer as well
* What do you use sqlean for?
I have used the UUID extension for a freelance application.
* What is the top 1 thing you miss in sqlean?
I'd love Ruby gem packages distributed as well. Alex Garcia has setup a GitHub Action workflow that releases to RubyGems alongside Python and Node and Deno and Go. You can see his extensions and how they support this from this directory project: https://github.com/asg017/sqlite-ecosystem

**Comment by terefang** [comment]
* What is your role in the organization? \
    Network Management Architect

* What do you use sqlean for? \
   ETL and Reports

* What is the top 1 thing you miss in sqlean?

    - out-of-the-box static build binary shell (ie. musl linked), because for various reasons i need provide a dependency-free standalone shell
    - a jdbc driver with sqlean enabled similar to the xerial one for stock sqlite

**Comment by nalgeon** [comment]
Thanks everyone! Due to the lack of interest from the community and my lack of free time, I do not plan to spend much time on this project in the near future, so this topic is no longer relevant.
