### ISSUE TITLE
Is there a precompiled binaries for Android (Java or Kotlin)?

### ISSUE THREAD

**Issue by nalgeon** [nalgeon/sqlean#89]
> Is there a precompiled binaries for Android (Java or Kotlin)?

_Originally posted by @jepiqueau_

**Comment by nalgeon** [comment]
Nope.

**Comment by jepiqueau** [comment]
@nalgeon any plan to do this ?

**Comment by jepiqueau** [comment]
i would like to use the sqlite extensions on mobile (Android and iOS). I am the author of the @capacitor-community/sqlite plugin which run on Browser, Electron, iOS and Android App. I have a request from developers to add the load extension method to the plugin. Looking for SQLite loadable extension for testing i found your site i tested the math extension in DB Browser for SQlite and it works to make my mind before staring the implementation on the plugin

**Comment by nalgeon** [comment]
I'm afraid I know nothing about Android/iOS ecosystems. I have no idea how to compile SQLite extensions for these OS using GitHub Actions.

**Comment by jepiqueau** [comment]
@nalgeon ok thanks for your time. You can close the issue
