### ISSUE TITLE
extension for a specific string function: reverse()

### ISSUE THREAD

**Issue by wbob** [nalgeon/sqlean#9]
https://github.com/mayflower/sqlite-reverse-string was useful to me once, it has no dependencies, but could be obsoleted by a library encompassing more string functions

**Comment by little-brother** [comment]
It's already implemented in [math](https://github.com/nalgeon/sqlean/blob/main/docs/math.md) extension.

> provide mathematical and string extension functions for SQL queries using the loadable extensions mechanism. Math: acos, asin, atan, atn2, atan2, acosh, asinh, atanh, difference, degrees, radians, cos, sin, tan, cot, cosh, sinh, tanh, coth, exp, log, log10, power, sign, sqrt, square, ceil, floor, pi. String: replicate, charindex, leftstr, rightstr, ltrim, rtrim, trim, replace, **_reverse_**, proper, padl, padr, padc, strfilter. Aggregate: stdev, variance, mode, median, lower_quartile, upper_quartile.

**Comment by nalgeon** [comment]
It's not. `math` extension contains only math functions. I don't know the source of your quote, but it's not the docs.

**Comment by little-brother** [comment]
https://www.sqlite.org/contrib
https://www.sqlite.org/contrib/download/extension-functions.c?get=25

**Comment by nalgeon** [comment]
This is an old third-party extension, which has nothing to do with `math` extension.

**Comment by little-brother** [comment]
Yeah, I missed that you are using another _math_ extension.

**Comment by warmwaffles** [comment]
@nalgeon sounds like that reverse would actually be useful to have in the unicode extension since that is dealing with strings in general.

**Comment by nalgeon** [comment]
I am working on the `text` extension, `reverse()` will be there.

**Comment by nalgeon** [comment]
[Done](https://github.com/nalgeon/sqlean/blob/main/docs/text.md).

**Comment by wbob** [comment]
thank you! I was pleasantly suprised you included split_part (substring_index for mysqlers) too, an often used function
