### ISSUE TITLE
sqlean and fileio complain about GLIBC_2.33 missing 

### ISSUE THREAD

**Issue by veermans** [nalgeon/sqlean#90]
The complete package `sqlean.so` looked like a neat idea but it failed to load on Ubuntu 20.04.6 LTS (I cannot upgrade to 22). It seems that the issue is with `fileio.so`. 

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by sqlean.so)

Does `fileio.so` indeed need GLIBC > 2.31 (Ubuntu 20.04 version) or would recompiling against 2.31 suffice?

**Comment by nalgeon** [comment]
Thanks for noticing! Fixed in [0.21.6](https://github.com/nalgeon/sqlean/releases/0.21.6).
