### ISSUE TITLE
Golang bindings and amalgamation support

### ISSUE THREAD

**Issue by riyaz-ali** [nalgeon/sqlean#92]
Hi 👋 First of all, thanks for this super amazing library and set of extensions! Great work 👏 

Inspired [`sqlean.py`](https://github.com/nalgeon/sqlean.py) and based on code and discussion under #69, #79, #82 and #84, I started out with [`sqlean.go`](https://github.com/riyaz-ali/sqlean.go) project to provide `go` bindings for `sqlean`.

There I'm generating an amalgamation build, [`sqlean.c`](https://github.com/riyaz-ali/sqlean.go/blob/main/sqlean.c), using the script under [`tools/amalgamate.go`](https://github.com/riyaz-ali/sqlean.go/blob/main/tools/amalgamate.go).

Following are a couple of issues I ran into when trying to build the amalgamated sources:

1. I get _redefinition error_ for the symbol `utf8_lookup`. There seems to be two _static global_ variables under [`src/fuzzy/translit.c`](https://github.com/nalgeon/sqlean/blob/main/src/fuzzy/translit.c#L17-L22) and [`src/unicode/extension.c`](https://github.com/nalgeon/sqlean/blob/main/src/unicode/extension.c#L4265-L4270) that share the same name.

2. There's [a random `#ifdef __cplusplus`](https://github.com/nalgeon/sqlean/blob/main/src/unicode/extension.c#L217-L219) in `src/unicode/extension.c`, presumably to close a prior `extern "C" {` definition, without any matching opening clause. Caught this when skimming through the generated file. This might cause unexpected build failures under a `c++` compiler.

3. I'm also facing some difficulties compiling `src/regexp` (because of `pcre2`) but I think it can be overcome by laying out the amalgamation file more intelligently. I'll give it a shot and update.

For now, to go ahead with what's working I've disabled `src/fuzzy` and `src/regexp`.

**Comment by nalgeon** [comment]
Sorry I wasn't much help. I tried to make the symbols globally unique earlier, but the code got so ugly that I dropped the idea. I may revisit it one day.

If there is anything else I can do to make things easier for you, please let me know.

I see that `sqlean.go` currently includes 10 out of 12 extensions, which is pretty awesome. Thanks for implementing it!

**Comment by riyaz-ali** [comment]
No worries!

I found an alternative way by downloading and committing the source files from `sqlean` under `pkg/` directory in `sqlean.go`, committing them there and adding some boilerplate Go code to connect everything together. This requires an ongoing maintenance effort to keep the sources in sync (this isn't in the repo yet!)

I'd still prefer managing a single amalgamated file vs. a bunch of spread out C files. Besides, I think amalgamation would be helpful in other languages and / or stack as well (like `rust` or `android` maybe 🤔).

Besides that, all the efforts you've put in #84 makes building an amalgamation file really simple and straightforward. I understand a conscious effort like this would be required for every extension you add to the main set.

Would love to hear your thoughts on this!

**Comment by nalgeon** [comment]
I completely agree that a single amalgamated file would be great. I just haven't figured out how to implement it without making the code a mess. I should try again :)

Thanks for the `utf8_lookup` fix! I just released [0.21.7](https://github.com/nalgeon/sqlean/releases/tag/0.21.7) with it.
